fix compiling bug: kernel:time/posix-cpu-timers.c. almost revert fb486e8d07ee90aa5a78d92dec1b8d65fd4a259f
Only change:
WARN_ON_ONCE(!irqs_disabled());
to:
WARN_ON_ONCE_NONRT(!irqs_disabled());

NEED TO DO:
If we need to add posix rt timer for migration, etc., we ned to implementation
new hotplug state machine method.

bug info:
kernel/time/posix-cpu-timers.c: In function 'posix_cpu_thread_call':
>> kernel/time/posix-cpu-timers.c:1350:7: error: 'CPU_UP_CANCELED' undeclared (first use in this function)
   case CPU_UP_CANCELED:
        ^
   kernel/time/posix-cpu-timers.c:1350:7: note: each undeclared identifier is reported only once for each function it appears in
   kernel/time/posix-cpu-timers.c: In function 'posix_cpu_thread_init':
   >> kernel/time/posix-cpu-timers.c:1386:2: error: implicit declaration of function 'register_cpu_notifier' [-Werror=implicit-function-declaration]
         register_cpu_notifier(&posix_cpu_thread_notifier);
                                ^
   cc1: some warnings being treated as errors